export const REGISTRATION = 'REGISTRATION';
export const LOGIN = 'LOGIN';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';